config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :quizzes
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  devise_for :users
  get 'pages/welcome'
  get 'pages/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#welcome"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/option.rb
# == Schema Information
#
# Table name: options
#
#  id          :bigint           not null, primary key
#  label       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  question_id :bigint
#
# Indexes
#
#  index_options_on_question_id  (question_id)
#
class Option < ApplicationRecord
    belongs_to :question, optional: true

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :bigint           not null, primary key
#  description :integer          default(0)
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  quiz_id     :bigint
#
# Indexes
#
#  index_questions_on_quiz_id  (quiz_id)
#
class Question < ApplicationRecord
    belongs_to :quiz
    has_many :options
    accepts_nested_attributes_for :options
    enum :descriptions, { free_text: 0, one_selection: 1, multiple_selection: 2 }

end

app/models/quiz.rb
# == Schema Information
#
# Table name: quizzes
#
#  id          :bigint           not null, primary key
#  description :string
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Quiz < ApplicationRecord
    has_many :questions
    accepts_nested_attributes_for :questions

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  full_name              :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        pages_index_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end

  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: %i[ show edit update destroy ]

  # GET /quizzes or /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1 or /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
    @quiz.questions.build.options.build
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes or /quizzes.json
  def create

    @quiz = Quiz.new(quiz_params)
    
    respond_to do |format|
      if @quiz.save
        format.html { redirect_to quiz_url(@quiz), notice: "Quiz was successfully created." }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1 or /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to quiz_url(@quiz), notice: "Quiz was successfully updated." }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1 or /quizzes/1.json
  def destroy
    @quiz.destroy

    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: "Quiz was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quiz_params
      params.require(:quiz).permit(:title, :description,  questions_attributes: [:name, :description, options_attributes: [:label] ])
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
    def question_type(selected)
        types = ["Free Text", "Single selection", "Multiple Selection" ]
        return types[selected]
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
  </head>

  <body>
     <%= render 'shared/header' %>.
    <%= yield %>
  </body>
</html>

app/views/pages/welcome.html.erb
<h2>Page#welcome</h2>
<p>Find me in app/views/page/welcome.html.erb</p>

app/views/questions/_select.html.erb
<fieldset id="fieldset-0">
    <legend>Select the type of question</legend>
    <% Question.descriptions.each_with_index do | value, index | %>
      <div>
      <input type="radio"  data-target="quiz.radioButton" data-action="click->quiz#selectType" id= <%=value[0] %> name="radio-button-0" value= <%=value[1] %>>
      <label for=<%=value[0] %> ><%=value[0].humanize %> </label>
    </div>
    <% end %>
</fieldset>

app/views/quizzes/_form.html.erb
<div data-controller="quiz">
  <%= form_with(model: quiz) do |form| %>
    <% if quiz.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

        <ul>
          <% quiz.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description %>
    </div>
    <div id="question_form">
      <div  class="question-header" style="display: flex">
        <h3>Questions</h3>
        <a class = "button-34" data-action="click->quiz#addQuestion">+Add Questions</a>
      </div>
      <div class="create_question_form" id="create_question_0">
        <%= form.fields_for :questions, Question.new do |question_attributes|%>
          <%= question_attributes.label :name, "Question Title", class: "lbel" %>
          <%= question_attributes.text_field :name %>
          <%= render 'questions/select' %>.
          <% (1..4).each do |option| %>
            <div class="create-options  hide">
            <%= question_attributes.fields_for :options, Option.new do |option_attributes|%>
             <%= option_attributes.label :label, "Options*" %>
             <%= option_attributes.text_field :label, required: true %>
            <% end %>
           </div>
          <% end %>
        <% end %>
        <hr>
      </div>
   
    </div>
    <div>
      <%= form.submit  nil,  class: "button-76" %>
    </div>
  <% end %>
</div>

app/views/quizzes/_quiz.html.erb
<div id="<%= dom_id quiz %>">
  <p>
    <strong>Description:</strong>
    <%= quiz.description %>
  </p>
  <% quiz.questions.each_with_index do | question, index | %>
    <div id="">
    <p>
      <strong><%= (index+1)%>. <%= question.name %></strong>
      <%= Question.descriptions.key(question.description).humanize%>
    </p>
  </div>
    <% if question.options %>
        <% question.options.each do |opt| %>
          <p>
            <strong>Select Option:</strong>
            <%=  opt.label%>
          </p>
        <% end %>
    <% end %>
  <% end %>
</div>

app/views/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render "form", quiz: @quiz %>

<br>

<div>
  <%= link_to "Show this quiz", @quiz %> |
  <%= link_to "Back to quizzes", quizzes_path %>
</div>

app/views/quizzes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Quizzes</h1>

<div id="quizzes">
  <% @quizzes.each do |quiz| %>
    <%= quiz.title %>
    <%= render quiz %>
    <p>
      <%= link_to "Show this quiz", quiz %>
    </p>
  <% end %>
</div>

<%= link_to "New quiz", new_quiz_path %>

app/views/quizzes/new.html.erb
<div class="cntainer">
  <h1>New quiz</h1>
  <%= render "form", quiz: @quiz %>
</div>

app/views/quizzes/show.html.erb
<div class="cntainer">ç
<h2 style="text-align:center;"><%= @quiz.title %></h2>
  <%= render @quiz %>

  <div>
    <%= link_to "Edit this quiz", edit_quiz_path(@quiz) %> |
    <%= link_to "Back to quizzes", quizzes_path %>
    <%= button_to "Destroy this quiz", @quiz, method: :delete %>
  </div>
</div>

app/views/shared/_header.html.erb
<header>
<span>
  <a href=<%= root_path %>>
    QuizApp
  </a>
  </span>
  <span style="float:right;">
  <% if current_user.present? %>
    <%= link_to "Quiz", quizzes_path , class: "button-29"%>
    <%= link_to "Dashboard", pages_index_path , class: "button-29"%>
    <%= link_to "Log Out", destroy_user_session_path, class: "button-29", method: :delete %>
  <%else%>
    <%= link_to "Login", new_user_session_path, class: "button-29" %>
    <%= link_to "Create Account", new_user_registration_path, class: "button-29" %>
  <% end %>
  </span>

</header>